app = 'real-time-chat-app'
primary_region = 'gru'

[build]
dockerfile = 'Dockerfile'
[build.args]
VITE_REVERB_APP_KEY = "${ VITE_REVERB_APP_KEY}"

# This `[[services]]` block is the explicit replacement for `[http_service]`
# It gives us the control needed to fix the redirect loop.
[[services]]
protocol = 'tcp'
internal_port = 80 # Caddy's default HTTP port
processes = ['app'] # Tells Fly to run the default 'app' process from the Dockerfile

# These are the important free-tier settings from your original file
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

# This section tells the Fly proxy how to handle traffic
[[services.ports]]
port = 80
handlers = ['http']
force_https = true # The proxy handles the HTTP -> HTTPS redirect

[[services.ports]]
port = 443
handlers = ['tls', 'http'] # The proxy handles the HTTPS certificate

# We'll keep the machine size definition from your original file
[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1