# Defines the version of the render.yaml blueprint specification.
version: 1

# Link to the environment you already created in the Render dashboard.
environment:
  name: real_time_chat_app_api # The name you gave your environment.
  fromExisting: true

services:
  # ------ BACKEND SERVICES ------

  # 1. The main Laravel Web Service (Nginx + FPM)
  - type: web
    name: nexus-chat-api
    env: php
    plan: free
    # CRITICAL: Specifies the directory for this service.
    rootDir: ./chat-api
    healthCheckPath: /up
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
      # IMPORTANT: Run migrations during the build to prevent race conditions.
      - command: "php artisan migrate:fresh --seed --force"
    startCommand: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    envVars:
      - key: APP_URL
        value: "${RENDER_EXTERNAL_URL}"
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          type: static
          name: real-time-chat-app
          property: host
      - key: REVERB_HOST
        fromService:
          type: pserv # Corrected type
          name: nexus-chat-reverb
          property: host

  # 2. The Laravel Reverb WebSocket Server
  - type: pserv # CORRECTED: The type for a Private Service is "pserv"
    name: nexus-chat-reverb
    env: php
    plan: free
    # CRITICAL: Specifies the directory for this service.
    rootDir: ./chat-api
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
    startCommand: "php artisan reverb:start --host=0.0.0.0 --port=10001"
    envVars:
      - key: REVERB_SERVER_PORT
        value: 10001

  # 3. The Queue Worker
  - type: worker
    name: nexus-chat-worker
    env: php
    plan: free
    # CRITICAL: Specifies the directory for this service.
    rootDir: ./chat-api
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
    startCommand: "php artisan queue:work --tries=3"

  # ------ FRONTEND SERVICE ------

  # 4. The React Static Site
  - type: static
    name: real-time-chat-app
    plan: free
    # CRITICAL: This service runs from the root where package.json is.
    rootDir: ./
    build:
      - command: "npm install && npm run build"
    # This directory is served on Render's CDN.
    publishDir: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nexus-chat-api
          property: url
      - key: VITE_REVERB_APP_KEY
        fromSync:
          environment: real_time_chat_app_api
          key: REVERB_APP_KEY
      - key: VITE_REVERB_HOST
        fromService:
          type: pserv # Corrected type
          name: nexus-chat-reverb
          property: host
      - key: VITE_REVERB_PORT
        value: 10001
      - key: VITE_REVERB_SCHEME
        value: wss