# render.yaml

version: 1

environment:
  name: real_time_chat_app_api
  fromExisting: true

services:
  # ------ BACKEND SERVICES ------
  - type: web
    name: nexus-chat-api
    runtime: php
    plan: free
    rootDir: ./chat-api
    healthCheckPath: /up
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
      - command: "php artisan migrate:fresh --seed --force"
    startCommand: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: nexus-chat-api
          property: url
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          type: static_site # CORRECTED
          name: real-time-chat-app
          property: host
      - key: REVERB_HOST
        fromService:
          type: pserv
          name: nexus-chat-reverb
          property: host

  - type: pserv
    name: nexus-chat-reverb
    runtime: php
    plan: free
    rootDir: ./chat-api
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
    startCommand: "php artisan reverb:start --host=0.0.0.0 --port=10001"
    envVars:
      - key: REVERB_SERVER_PORT
        value: 10001

  - type: worker
    name: nexus-chat-worker
    runtime: php
    plan: free
    rootDir: ./chat-api
    build:
      - command: "composer install --no-dev --optimize-autoloader"
      - command: "php artisan optimize:clear"
    startCommand: "php artisan queue:work --tries=3"

  # ------ FRONTEND SERVICE ------
  - type: static_site # CORRECTED
    name: real-time-chat-app
    plan: free
    rootDir: ./
    build:
      - command: "npm install && npm run build"
    publishDir: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nexus-chat-api
          property: url
      - key: VITE_REVERB_APP_KEY
        fromSync:
          environment: real_time_chat_app_api
          key: REVERB_APP_KEY
      - key: VITE_REVERB_HOST
        fromService:
          type: pserv
          name: nexus-chat-reverb
          property: host
      - key: VITE_REVERB_PORT
        value: 10001
      - key: VITE_REVERB_SCHEME
        value: wss