app = 'nexus-chat-api'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
[build.args]
NODE_VERSION = '18'
PHP_VERSION = '8.2'

[env]
APP_ENV = 'production'
APP_DEBUG = false
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'info'
SESSION_DRIVER = 'database'
CACHE_STORE = 'database'
QUEUE_CONNECTION = 'database'
DB_CONNECTION = 'pgsql'
APP_URL = "https://nexus-chat-api.fly.dev"
FRONTEND_URL = "https://real-time-chat-app.fly.dev"
SANCTUM_STATEFUL_DOMAINS = "real-time-chat-app.fly.dev"
BROADCAST_CONNECTION = 'reverb'
REVERB_HOST = "nexus-chat-api.fly.dev"
REVERB_PORT = 443
REVERB_SCHEME = "https"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app', 'reverb']

# Reverb process added back for WebSocket functionality
[processes]
app = "supervisord -c /etc/supervisor/supervisord.conf"
worker = "php artisan queue:work"
reverb = "php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=8081"

# The conflicting [[services]] blocks have been removed

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
