app = 'chat-api-falling-dream-7373'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[build]
dockerfile = 'Dockerfile'

[deploy]
release_command = '/var/www/html/.fly/scripts/release-tasks.sh'

[processes]
# The "app" process will run the container's default ENTRYPOINT (supervisord)
app = ""
reverb = 'php artisan reverb:start --host=0.0.0.0 --port=8080'
worker = 'php artisan queue:work --tries=3'

# HTTP Service for the main API (now points to the 'app' process)
[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['app'] # Changed from ['web']

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

# WebSocket Service for Reverb (no changes needed here)
[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['reverb']

[[services.ports]]
port = 443
handlers = ['tls', 'http']
