# File: chat-api/fly.toml
app = 'nexus-chat-api'
primary_region = 'gru'

[build]
image = 'flyio/laravel'

[env]
APP_ENV = 'production'
APP_DEBUG = false
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'info'
SESSION_DRIVER = 'database'
CACHE_STORE = 'database'
QUEUE_CONNECTION = 'database'
DB_CONNECTION = 'pgsql'
APP_URL = "https://nexus-chat-api.fly.dev"
FRONTEND_URL = "https://real-time-chat-app.fly.dev"
SANCTUM_STATEFUL_DOMAINS = "real-time-chat-app.fly.dev"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

# This section is for Reverb (Websockets)
[[services]]
protocol = 'tcp'
internal_port = 8081
processes = ['reverb']

[[services.ports]]
port = 443
handlers = ['tls']

[processes]
reverb = "php artisan reverb:start --host=0.0.0.0 --port=8081"
worker = "php artisan queue:work"
