app = 'chat-api-falling-dream-7373'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[build]
dockerfile = 'Dockerfile'

[deploy]
release_command = 'php artisan migrate:fresh --seed --force'

[processes]
web = 'php artisan serve --host=0.0.0.0 --port=8080'
reverb = 'php artisan reverb:start'
worker = 'php artisan queue:work --tries=3'

[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['web']

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']
