app = 'chat-api-falling-dream-7373'
primary_region = 'gru'

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
APP_URL = "https://chat-api-falling-dream-7373.fly.dev"
DB_CONNECTION = "pgsql"

[build]
dockerfile = 'Dockerfile'

[deploy]
release_command = '/var/www/html/.fly/scripts/release-tasks.sh'

[processes]
app = ""
reverb = 'php artisan reverb:start --host=0.0.0.0 --port=8081'
worker = 'php artisan queue:work --tries=3'

[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

# This separate service is for Reverb WebSockets
[[services]]
protocol = 'tcp'
internal_port = 8081
processes = ['reverb']

[[services.ports]]
port = 443
# Use the 'tls' handler for WebSockets, not 'http'
handlers = ['tls']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
