app = 'nexus-chat-api'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
[build.args]
NODE_VERSION = '18'
PHP_VERSION = '8.2'

[env]
APP_ENV = 'production'
APP_DEBUG = false
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'info'
SESSION_DRIVER = 'database'
CACHE_STORE = 'database'
QUEUE_CONNECTION = 'database'
DB_CONNECTION = 'pgsql'
APP_URL = "https://nexus-chat-api.fly.dev"
FRONTEND_URL = "https://real-time-chat-app.fly.dev"
SANCTUM_STATEFUL_DOMAINS = "real-time-chat-app.fly.dev"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# This is the change: The reverb process is removed
[processes]
app = "supervisord -c /etc/supervisor/supervisord.conf"
worker = "php artisan queue:work"

# The conflicting [[services]] blocks have been removed

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
